
-- ==========================================
-- 1. ТАБЛИЦА ПРОФИЛЕЙ И АВТО-РЕГИСТРАЦИЯ
-- ==========================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE,
    first_name TEXT,
    photo_url TEXT,
    rating DECIMAL DEFAULT 5.0,
    points INTEGER DEFAULT 100,
    is_pro BOOLEAN DEFAULT false,
    is_admin BOOLEAN DEFAULT false,
    is_verified BOOLEAN DEFAULT false,
    is_reliable BOOLEAN DEFAULT true,
    is_banned BOOLEAN DEFAULT false,
    referral_code TEXT UNIQUE,
    referred_by_id UUID REFERENCES public.profiles(id),
    deals_count INTEGER DEFAULT 0,
    is_donor BOOLEAN DEFAULT false,
    level TEXT DEFAULT 'Мужик',
    specialization TEXT[] DEFAULT '{}',
    portfolio_images TEXT[] DEFAULT '{}',
    trusted_contacts TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Функция для автоматического создания профиля при регистрации в Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, first_name, photo_url, referral_code)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', 'user_' || substr(new.id::text, 1, 8)),
    COALESCE(new.raw_user_meta_data->>'first_name', 'Мужик'),
    new.raw_user_meta_data->>'photo_url',
    'M' || substr(new.id::text, 1, 8)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Триггер: срабатывает сразу после записи в auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================
-- 2. РАБОТА И ОБЪЯВЛЕНИЯ
-- ==========================================

-- Вакансии
CREATE TABLE IF NOT EXISTS public.vacancies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    company_name TEXT DEFAULT 'ЦЕХ Контракт',
    salary TEXT,
    region TEXT,
    city_id TEXT,
    is_vahta BOOLEAN DEFAULT false,
    vakhta_duration TEXT,
    is_verified_vakhta BOOLEAN DEFAULT false,
    housing BOOLEAN DEFAULT true,
    food BOOLEAN DEFAULT false,
    travel BOOLEAN DEFAULT false,
    description TEXT,
    contact TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Услуги мастеров
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    category TEXT,
    title TEXT NOT NULL,
    description TEXT,
    price TEXT,
    author TEXT,
    contact TEXT,
    city_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Барахолка (Marketplace)
CREATE TABLE IF NOT EXISTS public.market_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    type TEXT CHECK (type IN ('SELL', 'BUY')),
    category TEXT,
    title TEXT NOT NULL,
    price TEXT,
    condition TEXT,
    description TEXT,
    contact TEXT,
    city_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ==========================================
-- 3. ЖУРНАЛЫ И ЗАМЕТКИ
-- ==========================================

-- Журнал Вахты (Сметы)
CREATE TABLE IF NOT EXISTS public.vakhta_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE,
    expected_salary INTEGER DEFAULT 0,
    advances INTEGER DEFAULT 0,
    travel_expenses INTEGER DEFAULT 0,
    food_expenses INTEGER DEFAULT 0,
    sent_home INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Бортовой журнал (Заметки)
CREATE TABLE IF NOT EXISTS public.notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Общий Эфир (Лента)
CREATE TABLE IF NOT EXISTS public.feed_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    image_url TEXT,
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ==========================================
-- 4. ЛОГИСТИКА И ТЕХНИКА
-- ==========================================

-- Попутчики
CREATE TABLE IF NOT EXISTS public.hitchhikers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    name TEXT,
    route_from TEXT NOT NULL,
    route_to TEXT NOT NULL,
    departure_date DATE,
    price TEXT,
    car_model TEXT,
    seats INTEGER DEFAULT 1,
    can_take_cargo BOOLEAN DEFAULT false,
    description TEXT,
    contact TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Попутные грузы
CREATE TABLE IF NOT EXISTS public.cargo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    route_from TEXT,
    route_to TEXT,
    cargo_type TEXT,
    weight TEXT,
    price TEXT,
    departure_date DATE,
    description TEXT,
    contact TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Спецтехника
CREATE TABLE IF NOT EXISTS public.machinery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    type TEXT,
    model TEXT,
    rate TEXT,
    city_id TEXT,
    description TEXT,
    contact TEXT,
    includes_operator BOOLEAN DEFAULT true,
    includes_fuel BOOLEAN DEFAULT true,
    specs TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Бригады
CREATE TABLE IF NOT EXISTS public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    leader TEXT,
    category TEXT,
    member_count INTEGER DEFAULT 1,
    structure JSONB DEFAULT '[]',
    equipment TEXT[] DEFAULT '{}',
    description TEXT,
    rating DECIMAL DEFAULT 5.0,
    city_id TEXT,
    contact TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ==========================================
-- 5. СЛУЖЕБНЫЕ ТАБЛИЦЫ
-- ==========================================

-- SOS Сигналы
CREATE TABLE IF NOT EXISTS public.sos_signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    user_name TEXT,
    scenario TEXT,
    lat DECIMAL,
    lng DECIMAL,
    status TEXT DEFAULT 'SENT',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Заявки на верификацию
CREATE TABLE IF NOT EXISTS public.verification_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    full_name TEXT,
    specialization TEXT,
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Донаты и поддержка
CREATE TABLE IF NOT EXISTS public.donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    pack_id INTEGER,
    pack_name TEXT,
    stars_amount INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- ==========================================
-- 6. ПРАВИЛА БЕЗОПАСНОСТИ (RLS)
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vacancies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.market_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vakhta_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feed_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hitchhikers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cargo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machinery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sos_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

-- Удаляем старые политики перед созданием (защита от ошибок 42710)
DROP POLICY IF EXISTS "Profiles viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Profiles viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Vacancies viewable by everyone" ON public.vacancies;
DROP POLICY IF EXISTS "Vacancies insertable by authenticated" ON public.vacancies;
DROP POLICY IF EXISTS "Vacancies deletable by author" ON public.vacancies;
CREATE POLICY "Vacancies viewable by everyone" ON public.vacancies FOR SELECT USING (true);
CREATE POLICY "Vacancies insertable by authenticated" ON public.vacancies FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Vacancies deletable by author" ON public.vacancies FOR DELETE USING (auth.uid() = author_id);

DROP POLICY IF EXISTS "Services viewable by everyone" ON public.services;
DROP POLICY IF EXISTS "Services insertable by author" ON public.services;
DROP POLICY IF EXISTS "Services deletable by author" ON public.services;
CREATE POLICY "Services viewable by everyone" ON public.services FOR SELECT USING (true);
CREATE POLICY "Services insertable by author" ON public.services FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Services deletable by author" ON public.services FOR DELETE USING (auth.uid() = author_id);

DROP POLICY IF EXISTS "Market viewable by everyone" ON public.market_items;
DROP POLICY IF EXISTS "Market insertable by author" ON public.market_items;
DROP POLICY IF EXISTS "Market deletable by author" ON public.market_items;
CREATE POLICY "Market viewable by everyone" ON public.market_items FOR SELECT USING (true);
CREATE POLICY "Market insertable by author" ON public.market_items FOR INSERT WITH CHECK (auth.uid() = author_id);
CREATE POLICY "Market deletable by author" ON public.market_items FOR DELETE USING (auth.uid() = author_id);

DROP POLICY IF EXISTS "Notes are private" ON public.notes;
CREATE POLICY "Notes are private" ON public.notes FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Vakhta journal is private" ON public.vakhta_entries;
CREATE POLICY "Vakhta journal is private" ON public.vakhta_entries FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Feed viewable by everyone" ON public.feed_posts;
DROP POLICY IF EXISTS "Feed insertable by author" ON public.feed_posts;
CREATE POLICY "Feed viewable by everyone" ON public.feed_posts FOR SELECT USING (true);
CREATE POLICY "Feed insertable by author" ON public.feed_posts FOR INSERT WITH CHECK (auth.uid() = author_id);

DROP POLICY IF EXISTS "Hitchhikers viewable by everyone" ON public.hitchhikers;
DROP POLICY IF EXISTS "Hitchhikers insertable by author" ON public.hitchhikers;
CREATE POLICY "Hitchhikers viewable by everyone" ON public.hitchhikers FOR SELECT USING (true);
CREATE POLICY "Hitchhikers insertable by author" ON public.hitchhikers FOR INSERT WITH CHECK (auth.uid() = author_id);

DROP POLICY IF EXISTS "Cargo viewable by everyone" ON public.cargo;
DROP POLICY IF EXISTS "Cargo insertable by author" ON public.cargo;
CREATE POLICY "Cargo viewable by everyone" ON public.cargo FOR SELECT USING (true);
CREATE POLICY "Cargo insertable by author" ON public.cargo FOR INSERT WITH CHECK (auth.uid() = author_id);

DROP POLICY IF EXISTS "Machinery viewable by everyone" ON public.machinery;
CREATE POLICY "Machinery viewable by everyone" ON public.machinery FOR SELECT USING (true);

DROP POLICY IF EXISTS "Teams viewable by everyone" ON public.teams;
CREATE POLICY "Teams viewable by everyone" ON public.teams FOR SELECT USING (true);

DROP POLICY IF EXISTS "SOS viewable by everyone" ON public.sos_signals;
DROP POLICY IF EXISTS "SOS insertable by author" ON public.sos_signals;
CREATE POLICY "SOS viewable by everyone" ON public.sos_signals FOR SELECT USING (true);
CREATE POLICY "SOS insertable by author" ON public.sos_signals FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Donations viewable by everyone" ON public.donations;
DROP POLICY IF EXISTS "Donations insertable by auth" ON public.donations;
CREATE POLICY "Donations viewable by everyone" ON public.donations FOR SELECT USING (true);
CREATE POLICY "Donations insertable by auth" ON public.donations FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ==========================================
-- ИНДЕКСЫ ДЛЯ СКОРОСТИ
-- ==========================================
CREATE INDEX IF NOT EXISTS vacancies_city_idx ON public.vacancies(city_id);
CREATE INDEX IF NOT EXISTS market_city_idx ON public.market_items(city_id);
CREATE INDEX IF NOT EXISTS profiles_referral_idx ON public.profiles(referral_code);
CREATE INDEX IF NOT EXISTS feed_created_idx ON public.feed_posts(created_at DESC);
